version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka0:
    build: .
    image: kafka-docker:latest
    ports:
        - "10000:10000"
    environment:
      KAFKA_LISTENERS: LISTENER_BOB://:29092,LISTENER_FRED://:10000
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:10000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka1:
    image: kafka-docker:latest
    ports:
        - "10001:10001"
    environment:
      KAFKA_LISTENERS: LISTENER_BOB://:29092,LISTENER_FRED://:10001
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka1:29092,LISTENER_FRED://localhost:10001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka2:
    image: kafka-docker:latest
    ports:
        - "10002:10002"
    environment:
      KAFKA_LISTENERS: LISTENER_BOB://:29092,LISTENER_FRED://:10002
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka2:29092,LISTENER_FRED://localhost:10002
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
